# agentic_workflow.py

# TODO: 1 - Import the following agents: ActionPlanningAgent, KnowledgeAugmentedPromptAgent, EvaluationAgent, RoutingAgent from the workflow_agents.base_agents module

import os

from config.env import load_env
from phase_1.workflow_agents.base_agents import ActionPlanningAgent, EvaluationAgent, KnowledgeAugmentedPromptAgent, \
    RoutingAgent
from services.llm_service import LLMService

load_env()
# TODO: 2 - Load the OpenAI key into a variable called openai_api_key
# No need to load the key as LLMService will handle that
service = LLMService()
# load the product spec
# TODO: 3 - Load the product spec document Product-Spec-Email-Router.txt into a variable called product_spec

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

file_path = os.path.join(BASE_DIR, "Product-Spec-Email-Router.txt")

with open(file_path, "r", encoding="utf-8") as f:
    product_spec = f.read()

# Instantiate all the agents

# Action Planning Agent
knowledge_action_planning = (
    "Stories are defined from a product spec by identifying a "
    "persona, an action, and a desired outcome for each story. "
    "Each story represents a specific functionality of the product "
    "described in the specification. \n"
    "Features are defined by grouping related user stories. \n"
    "Tasks are defined for each story and represent the engineering "
    "work required to develop the product. \n"
    "A development Plan for a product contains all these components"
)
# TODO: 4 - Instantiate an action_planning_agent using the 'knowledge_action_planning'
action_agent = ActionPlanningAgent(
    service=service,
    knowledge=knowledge_action_planning
)

# Product Manager - Knowledge Augmented Prompt Agent
persona_product_manager = "You are a Product Manager, you are responsible for defining the user stories for a product."
knowledge_product_manager = (
    "Stories are defined by writing sentences with a persona, an action, and a desired outcome. "
    "The sentences always start with: As a "
    "Write several stories for the product spec below, where the personas are the different users of the product. "
    "PRODUCT SPECIFICATION:\n"
    f"{product_spec}"
)

# TODO: 6 - Instantiate a product_manager_knowledge_agent using 'persona_product_manager' and the completed 'knowledge_product_manager'
product_manager = KnowledgeAugmentedPromptAgent(service=service,
                                                persona=persona_product_manager,
                                                knowledge=knowledge_product_manager)

# Product Manager - Evaluation Agent
# TODO: 7 - Define the persona and evaluation criteria for a Product Manager evaluation agent and instantiate it as product_manager_evaluation_agent. This agent will evaluate the product_manager_knowledge_agent.
# The evaluation_criteria should specify the expected structure for user stories (e.g., "As a [type of user], I want [an action or feature] so that [benefit/value].").

product_manager_evaluation_agent = EvaluationAgent(
    service=service,
    persona=(
        "You are a Senior Product Owner reviewing user stories generated by a Product Manager."
    ),
    evaluation_criteria=(
        "Evaluate whether the user stories meet the following criteria:\n"
        "1. Each story must strictly follow the format: "
        "'As a <type of user>, I want to <action>, so that <benefit/value>'.\n"
     #   "2. Personas must be valid users mentioned or implied in the product specification "
     #   "(e.g., Customer Support Representative, Subject Matter Expert, IT Administrator).\n"
     #   "3. Each story should describe a single, clear piece of functionality.\n"
     #  "4. The desired outcome must clearly express business or user value.\n"
     #   "5. Stories must be derived only from the provided product specification and "
     #   "must not introduce new or unrelated features.\n"
     #   "6. Stories should avoid technical implementation details and focus on user intent."
    ),
    worker_agent=product_manager,
    max_interactions=10
)


# Program Manager - Knowledge Augmented Prompt Agent
persona_program_manager = "You are a Program Manager, you are responsible for defining the features for a product."
knowledge_program_manager = "Features of a product are defined by organizing similar user stories into cohesive groups."
# Instantiate a program_manager_knowledge_agent using 'persona_program_manager' and 'knowledge_program_manager'
# (This is a necessary step before TODO 8. Students should add the instantiation code here.)

program_manager = KnowledgeAugmentedPromptAgent(service=service,
                                                persona=persona_program_manager,
                                                knowledge=knowledge_program_manager)


# Program Manager - Evaluation Agent
persona_program_manager_eval = "You are an evaluation agent that checks the answers of other worker agents."

# TODO: 8 - Instantiate a program_manager_evaluation_agent using 'persona_program_manager_eval' and the evaluation criteria below.
#                      "The answer should be product features that follow the following structure: " \
#                      "Feature Name: A clear, concise title that identifies the capability\n" \
#                      "Description: A brief explanation of what the feature does and its purpose\n" \
#                      "Key Functionality: The specific capabilities or actions the feature provides\n" \
#                      "User Benefit: How this feature creates value for the user"
# For the 'agent_to_evaluate' parameter, refer to the provided solution code's pattern.

program_manager_evaluation_agent = EvaluationAgent(
    service=service,
    persona=persona_program_manager_eval,
    evaluation_criteria=(
        "The answer should be product features that follow the following structure:\n"
        "Feature Name: A clear, concise title that identifies the capability\n"
        "Description: A brief explanation of what the feature does and its purpose\n"
        "Key Functionality: The specific capabilities or actions the feature provides\n"
        "User Benefit: How this feature creates value for the user\n"
        "Features must be derived from the provided user stories and should not "
        "introduce new functionality beyond the product specification."
    ),
    worker_agent=program_manager,
    max_interactions=10
)


# Development Engineer - Knowledge Augmented Prompt Agent
persona_dev_engineer = "You are a Development Engineer, you are responsible for defining the development tasks for a product."
knowledge_dev_engineer = "Development tasks are defined by identifying what needs to be built to implement each user story."
# Instantiate a development_engineer_knowledge_agent using 'persona_dev_engineer' and 'knowledge_dev_engineer'
# (This is a necessary step before TODO 9. Students should add the instantiation code here.)

development_engineer = KnowledgeAugmentedPromptAgent(
    service=service,
    persona=persona_dev_engineer,
    knowledge=knowledge_dev_engineer
)

# Development Engineer - Evaluation Agent
persona_dev_engineer_eval = "You are an evaluation agent that checks the answers of other worker agents."
# TODO: 9 - Instantiate a development_engineer_evaluation_agent using 'persona_dev_engineer_eval' and the evaluation criteria below.
#                      "The answer should be tasks following this exact structure: " \
#                      "Task ID: A unique identifier for tracking purposes\n" \
#                      "Task Title: Brief description of the specific development work\n" \
#                      "Related User Story: Reference to the parent user story\n" \
#                      "Description: Detailed explanation of the technical work required\n" \
#                      "Acceptance Criteria: Specific requirements that must be met for completion\n" \
#                      "Estimated Effort: Time or complexity estimation\n" \
#                      "Dependencies: Any tasks that must be completed first"
# For the 'agent_to_evaluate' parameter, refer to the provided solution code's pattern.

development_engineer_evaluation_agent = EvaluationAgent(
    service=service,
    persona=persona_dev_engineer_eval,
    evaluation_criteria=(
        "The answer should be tasks following this exact structure:\n"
        "Task ID: A unique identifier for tracking purposes\n"
        "Task Title: Brief description of the specific development work\n"
        "Related User Story: Reference to the parent user story\n"
        "Description: Detailed explanation of the technical work required\n"
        "Acceptance Criteria: Specific requirements that must be met for completion\n"
        "Estimated Effort: Time or complexity estimation\n"
        "Dependencies: Any tasks that must be completed first\n"
        "Tasks must be implementable, unambiguous, and derived from the defined features."
    ),
    worker_agent=development_engineer,
    max_interactions=10
)

# Routing Agent
# TODO: 10 - Instantiate a routing_agent. You will need to define a list of agent dictionaries (routes) for Product Manager, Program Manager, and Development Engineer. Each dictionary should contain 'name', 'description', and 'func' (linking to a support function). Assign this list to the routing_agent's 'agents' attribute.

def product_manager_support_function(step):
    response = product_manager.respond(step)
    validated_response = product_manager_evaluation_agent.evaluate(response)
    return validated_response


def program_manager_support_function(step):
    response = program_manager.respond(step)
    validated_response = program_manager_evaluation_agent.evaluate(response)
    return validated_response


def development_engineer_support_function(step):
    response = development_engineer.respond(step)
    validated_response = development_engineer_evaluation_agent.evaluate(response)
    return validated_response

agents = [
    {
        "name": "Product Manager",
        "description": "Defines user stories from the product specification",
        "func": product_manager_support_function
    },
    {
        "name": "Program Manager",
        "description": "Groups user stories into product features",
        "func": program_manager_support_function
    },
    {
        "name": "Development Engineer",
        "description": (    "Defines engineering tasks by breaking user stories and features "
                            "into detailed technical implementation work items."),
        "func": development_engineer_support_function
    }
]

routing_agent = RoutingAgent(service=service, agents=agents)

# Job function persona support functions
# TODO: 11 - Define the support functions for the routes of the routing agent (e.g., product_manager_support_function, program_manager_support_function, development_engineer_support_function).
# Each support function should:
#   1. Take the input query (e.g., a step from the action plan).
#   2. Get a response from the respective Knowledge Augmented Prompt Agent.
#   3. Have the response evaluated by the corresponding Evaluation Agent.
#   4. Return the final validated response.

# Run the workflow

print("\n*** Workflow execution started ***\n")
# Workflow Prompt
# ****
workflow_prompt = "What would the development tasks for this product be?"
# ****
print(f"Task to complete in this workflow, workflow prompt = {workflow_prompt}")

print("\nDefining workflow steps from the workflow prompt")
# TODO: 12 - Implement the workflow.
#   1. Use the 'action_planning_agent' to extract steps from the 'workflow_prompt'.
#   2. Initialize an empty list to store 'completed_steps'.
#   3. Loop through the extracted workflow steps:
#      a. For each step, use the 'routing_agent' to route the step to the appropriate support function.
#      b. Append the result to 'completed_steps'.
#      c. Print information about the step being executed and its result.
#   4. After the loop, print the final output of the workflow (the last completed step).

workflow_steps = action_agent.extract_steps_from_prompt(workflow_prompt)
print("DEBUG:", workflow_steps)
print("###################- Workflow steps -#########################")
for step in workflow_steps:
    print(f"Workflow step - {step}")

# for idx, step in enumerate(workflow_steps, start=1):
#     print(f"\n--- Executing workflow step {idx}: {step} ---")
#
#     agent_name = routing_agent.get_best_agent_name(step)
#
#     print(f"\nstep: {step}, agent name:{agent_name}")
#
# exit(0)
completed_steps = []

# Step 3: Execute workflow steps
for idx, step in enumerate(workflow_steps, start=1):
    print(f"\n--- Executing workflow step {idx}: {step} ---")

    result = routing_agent.route(step)

    completed_steps.append(result)

    print(f"\nResult of step {idx}:\n{result}")

# Step 4: Final output
print("\n*** Workflow execution completed ***\n")
print("Final Output ALL:\n")
print("############################################")
print(completed_steps)
print("#################Last Step##################")
print("Final Output Last Step:\n")
print(completed_steps[-1])